---
title: "課堂練習"
date: "9/12/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("C:/Users/kaiwun/ANACON~1/envs/myEnvironment",
           required = T)
use_condaenv("myEnvironment", required = T)
```

```{r}
library(reticulate)

```

```{r}
library(reticulate)
conda_create("myEnvironment")
```

```{python}
a=5
type(a) # check class type
```
```{python}
string = "你好"
string2 = '我很好' # 用單引號也可以
type(string)
numInteger = 3
type(numInteger)
#len(numInteger)
numFloat = 3.
type(numFloat)
#len(numFloat)
```
```{python}
logiT=True
type(logiT)
logiF=False
type(logiF)
```
```{python}
(2,3,(4,5)) # hashable
(2,3,[4,5]) # not hashable
```
```{python}
listA=[1,2,True]
listA
type(listA)
listB=[1,["a","b"],True]
listB
type(listB)
```
```{python}
tupleC=(1,["a","b"],True)
type(tupleC)
print(tupleC)
```

```{python}
setD={1,"a",(1,4)}
type(setD)
print(setD)
setE={True,False}
print(setE)
setF={1,"b",[1,4]}
```
```{python}
listY=[1,1,3,0,1,0,2]
list(set(listY))
```